repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: debug-statements
  - repo: https://github.com/psf/black
    rev: 23.12.0
    hooks:
      - id: black
