name: example black
on: 
jobs:
        format:
                runs-on: ubuntu-latest
                steps:
                  - uses: actions/checkout@v4
                  - uses: actions/setup-python@v4
                  - run: pip install black
                  - run: black . --check
